id: P000716
initial_creation_type: ocr
source_metadata:
  id: bdr:W23937
  title: ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར་ནོར་བུའི་བང་མཛོད་སོགས
  author: ''
  volumes:
    7cf33c1881fe48ffbba56077379d8c50:
      image_group_id: I2DB80588
      title: ''
      volume_number: 1
      total_pages: 59
      base_file: v001.txt
