id: ID24422F9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:52:26+00:00'
last_modified: '2022-06-07T12:44:19.998176+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23937
  title: ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར་ནོར་བུའི་བང་མཛོད་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8E0A:
      image_group_id: I2DB80588
      title: ''
      total_pages: 59
      order: 1
      base_file: 8E0A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
