id: ID24422F9
legacy_id: P000716
ocr_import_info:
  bdrc_scan_id: W23937
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T23:52:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:20:10.027704+00:00'
last_modified: 2022-09-02 13:20:20.250334
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23937
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23937
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར་ནོར་བུའི་བང་མཛོད་སོགས།
  author: ཟང་ཟང་ནེ་རིང་པ་འཆི་མེད་རབ་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.9328336155282719
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I2DB80588:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2DB80588
      total_pages: 59
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2DB80588.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9328336155282719
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
